### ISSUE TITLE
Standardize field names in data model files

### ISSUE THREAD

**Issue by bruth** [chop-dbhi/data-models#5]
The purpose of this file is to make it possible to translate the files into a common format for downstream consumption.

Table definition file fields: `tables.csv`

- `model` (required) - Name of the model
- `version` (required) - Version of the model
- `table` (required) - Name of the table
- `label` - Label for the table.
- `description` - Description of the table.

Field definition file fields: `definitions/<table>.csv`

- `model` (required) - Name of the model.
- `version` (required) - Version of the model.
- `table` (required) - Name of the table.
- `field` (required) - Name of the field.
- `label` - Corresponds to the field label. This defaults to `table` + `field`
- `description` - Corresponds to the description or documentation of the field.
- `type` - Describes the data type of the value the field holds.
- `ref_table` - The table this field references.
- `ref_field` - The field this field references.

Field schema file fields: `schema/<table>.csv`

- `model` (required) - Name of the model.
- `version` (required) - Version of the model.
- `table` (required) - Name of the table.
- `field` (required) - Name of the field.
- `type` (required) - Data type of the field.
- `length` - Describes the maximum length of the value.
- `precision` - Describes the precision of value specified in `type`, typically for a number.
- `scale` - Describes the scale of the value specified in `type`, typically for a number.
- `default` - Defines the default value for the field.

Constraints file fields: `constraints/<table>.csv`

- `model` (required) - Name of the model.
- `version` (required) - Version of the model.
- `table` (required) - Table the constraint applies to.
- `fields` - One or more fields the constraint applies to.
- `type` (required) - Type of constraint.
- `name` - Suggested name of the constraint

Indexes file fields: `indexes/<table>.csv`

- `model` (required) - Name of the model.
- `version` (required) - Version of the model.
- `table` (required) - Name of the table.
- `fields` (required) - One or more fields the index applies.
- `name` - Suggested name of the index.
- `type` - Suggested type of the index.

**Comment by bruth** [comment]
A little program can read in the original file, performing the mapping and output a "normalized" file.

**Comment by aaron0browne** [comment]
Any room for expanding the common format described above to include table-level attributes? Or are you just thinking consumers will get table names from the field descriptions (and not get multi-column unique constraints, indexes, primary keys, etc.)?

**Comment by bruth** [comment]
I presume we could generalize this an have the metadata file describe the entities in the file, e.g:

```yaml
table: 
    path:
        - Table

field:
    path:
        - Table
        - Field
    doc: Description
    type: Type Precision
    required: Required
```

This would allow for supporting all kinds of variables since it is opt-in.

**Comment by bruth** [comment]
By *file* I mean the flat files containing information about the data model (those the repository).

**Comment by bruth** [comment]
A logical extension would be to specify which files should be considered when parsing:

```yaml
table: 
    files: ./tables.csv
    path:
        - Table

field:
    files: ./fields/*.csv
    path:
        - Table
        - Field
    doc: Description
    type: Type Precision
    required: Required
```
